# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'lainauspalautus.ui'
##
## Created by: Qt User Interface Compiler version 6.11.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDateEdit, QFrame,
    QHeaderView, QLabel, QMainWindow, QMenuBar,
    QPushButton, QSizePolicy, QStackedWidget, QStatusBar,
    QTableWidget, QTableWidgetItem, QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(449, 547)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(10, 0, 431, 491))
        self.stackedWidget.setStyleSheet(u"background-color: rgb(0, 149, 178);\n"
"background-color: rgb(223, 32, 112);")
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.frame = QFrame(self.page)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(110, 170, 211, 231))
        self.frame.setStyleSheet(u"background-color: rgb(27, 50, 89);")
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.lainausnappi = QPushButton(self.frame)
        self.lainausnappi.setObjectName(u"lainausnappi")
        self.lainausnappi.setGeometry(QRect(20, 20, 171, 51))
        self.lainausnappi.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.palautusnappi = QPushButton(self.frame)
        self.palautusnappi.setObjectName(u"palautusnappi")
        self.palautusnappi.setGeometry(QRect(20, 90, 171, 51))
        self.palautusnappi.setStyleSheet(u"background-color: rgb(239, 239, 239);")
        self.historianappi = QPushButton(self.frame)
        self.historianappi.setObjectName(u"historianappi")
        self.historianappi.setGeometry(QRect(20, 160, 171, 51))
        self.historianappi.setStyleSheet(u"background-color: rgb(239, 239, 239);")
        self.tervetuloa = QTextEdit(self.page)
        self.tervetuloa.setObjectName(u"tervetuloa")
        self.tervetuloa.setGeometry(QRect(90, 90, 241, 41))
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.frame_6 = QFrame(self.page_2)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(50, 60, 341, 401))
        self.frame_6.setStyleSheet(u"background-color: rgb(0, 149, 178);")
        self.frame_6.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Shadow.Raised)
        self.otsikkolainaus = QLabel(self.frame_6)
        self.otsikkolainaus.setObjectName(u"otsikkolainaus")
        self.otsikkolainaus.setGeometry(QRect(120, 30, 101, 16))
        self.otsikkolainaus.setMaximumSize(QSize(101, 16))
        self.otsikkolainaus.setStyleSheet(u"")
        self.lainauksenvalikoima = QComboBox(self.frame_6)
        self.lainauksenvalikoima.setObjectName(u"lainauksenvalikoima")
        self.lainauksenvalikoima.setGeometry(QRect(40, 80, 261, 21))
        self.lainauksenvalikoima.setStyleSheet(u"background-color: rgb(239, 239, 239);\n"
"")
        self.lainausvalikoimalista = QTableWidget(self.frame_6)
        if (self.lainausvalikoimalista.columnCount() < 2):
            self.lainausvalikoimalista.setColumnCount(2)
        __qtablewidgetitem = QTableWidgetItem()
        self.lainausvalikoimalista.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.lainausvalikoimalista.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        if (self.lainausvalikoimalista.rowCount() < 1):
            self.lainausvalikoimalista.setRowCount(1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.lainausvalikoimalista.setVerticalHeaderItem(0, __qtablewidgetitem2)
        self.lainausvalikoimalista.setObjectName(u"lainausvalikoimalista")
        self.lainausvalikoimalista.setGeometry(QRect(20, 150, 301, 101))
        self.lainausvalikoimalista.setStyleSheet(u"background-color: rgb(239, 239, 239);\n"
"gridline-color: rgb(27, 50, 89);")
        self.frame_2 = QFrame(self.frame_6)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(200, 300, 131, 91))
        self.frame_2.setStyleSheet(u"background-color: rgb(27, 50, 89);\n"
"")
        self.frame_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Shadow.Raised)
        self.palaanappilainauksessa = QPushButton(self.frame_2)
        self.palaanappilainauksessa.setObjectName(u"palaanappilainauksessa")
        self.palaanappilainauksessa.setGeometry(QRect(10, 10, 111, 31))
        self.palaanappilainauksessa.setStyleSheet(u"background-color: rgb(239, 239, 239);")
        self.vahvistanappilainauksessa = QPushButton(self.frame_2)
        self.vahvistanappilainauksessa.setObjectName(u"vahvistanappilainauksessa")
        self.vahvistanappilainauksessa.setGeometry(QRect(10, 50, 111, 31))
        self.vahvistanappilainauksessa.setStyleSheet(u"background-color: rgb(239, 239, 239);")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.frame_7 = QFrame(self.page_3)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setGeometry(QRect(60, 80, 321, 361))
        self.frame_7.setStyleSheet(u"background-color: rgb(0, 149, 178);")
        self.frame_7.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_3 = QFrame(self.frame_7)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(180, 260, 131, 91))
        self.frame_3.setStyleSheet(u"background-color: rgb(27, 50, 89);")
        self.frame_3.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Shadow.Raised)
        self.palaanappipalautuksessa = QPushButton(self.frame_3)
        self.palaanappipalautuksessa.setObjectName(u"palaanappipalautuksessa")
        self.palaanappipalautuksessa.setGeometry(QRect(10, 10, 111, 31))
        self.palaanappipalautuksessa.setStyleSheet(u"background-color: rgb(239, 239, 239);")
        self.vahvistanappipalautuksessa = QPushButton(self.frame_3)
        self.vahvistanappipalautuksessa.setObjectName(u"vahvistanappipalautuksessa")
        self.vahvistanappipalautuksessa.setGeometry(QRect(10, 50, 111, 31))
        self.vahvistanappipalautuksessa.setStyleSheet(u"background-color: rgb(239, 239, 239);")
        self.palautus = QTextEdit(self.frame_7)
        self.palautus.setObjectName(u"palautus")
        self.palautus.setGeometry(QRect(70, 80, 191, 41))
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.frame_8 = QFrame(self.page_4)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setGeometry(QRect(20, 30, 391, 431))
        self.frame_8.setStyleSheet(u"background-color: rgb(75, 188, 197);")
        self.frame_8.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QFrame.Shadow.Raised)
        self.historia = QLabel(self.frame_8)
        self.historia.setObjectName(u"historia")
        self.historia.setGeometry(QRect(150, 20, 101, 16))
        self.historia.setMaximumSize(QSize(101, 16))
        self.frame_5 = QFrame(self.frame_8)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(40, 80, 311, 101))
        self.frame_5.setStyleSheet(u"\n"
"background-color: rgb(27, 50, 89);")
        self.frame_5.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Shadow.Raised)
        self.haenappi = QPushButton(self.frame_5)
        self.haenappi.setObjectName(u"haenappi")
        self.haenappi.setGeometry(QRect(210, 20, 81, 31))
        self.haenappi.setStyleSheet(u"background-color: rgb(239, 239, 239);")
        self.tavarahistoriassa = QComboBox(self.frame_5)
        self.tavarahistoriassa.addItem("")
        self.tavarahistoriassa.setObjectName(u"tavarahistoriassa")
        self.tavarahistoriassa.setGeometry(QRect(10, 40, 161, 21))
        self.tavarahistoriassa.setStyleSheet(u"background-color: rgb(239, 239, 239);")
        self.henkilohistoriassa = QComboBox(self.frame_5)
        self.henkilohistoriassa.addItem("")
        self.henkilohistoriassa.addItem("")
        self.henkilohistoriassa.setObjectName(u"henkilohistoriassa")
        self.henkilohistoriassa.setGeometry(QRect(10, 70, 161, 22))
        self.henkilohistoriassa.setStyleSheet(u"background-color: rgb(239, 239, 239);")
        self.paivahistoriassa = QDateEdit(self.frame_5)
        self.paivahistoriassa.setObjectName(u"paivahistoriassa")
        self.paivahistoriassa.setGeometry(QRect(10, 10, 161, 22))
        self.paivahistoriassa.setStyleSheet(u"background-color: rgb(239, 239, 239);")
        self.haunperuutusnappi = QPushButton(self.frame_5)
        self.haunperuutusnappi.setObjectName(u"haunperuutusnappi")
        self.haunperuutusnappi.setGeometry(QRect(210, 60, 81, 31))
        self.haunperuutusnappi.setStyleSheet(u"background-color: rgb(239, 239, 239);")
        self.historialista = QTableWidget(self.frame_8)
        if (self.historialista.columnCount() < 2):
            self.historialista.setColumnCount(2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.historialista.setHorizontalHeaderItem(0, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.historialista.setHorizontalHeaderItem(1, __qtablewidgetitem4)
        if (self.historialista.rowCount() < 3):
            self.historialista.setRowCount(3)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.historialista.setVerticalHeaderItem(0, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.historialista.setVerticalHeaderItem(1, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.historialista.setVerticalHeaderItem(2, __qtablewidgetitem7)
        self.historialista.setObjectName(u"historialista")
        self.historialista.setGeometry(QRect(30, 210, 341, 131))
        self.historialista.setStyleSheet(u"background-color: rgb(239, 239, 239);\n"
"gridline-color: rgb(27, 50, 89);")
        self.frame_4 = QFrame(self.frame_8)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(240, 360, 131, 51))
        self.frame_4.setStyleSheet(u"background-color: rgb(27, 50, 89);")
        self.frame_4.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Shadow.Raised)
        self.palaanappihistoriassa = QPushButton(self.frame_4)
        self.palaanappihistoriassa.setObjectName(u"palaanappihistoriassa")
        self.palaanappihistoriassa.setGeometry(QRect(10, 10, 111, 31))
        self.palaanappihistoriassa.setStyleSheet(u"background-color: rgb(239, 239, 239);")
        self.stackedWidget.addWidget(self.page_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 449, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.lainausnappi, self.palautusnappi)
        QWidget.setTabOrder(self.palautusnappi, self.lainauksenvalikoima)
        QWidget.setTabOrder(self.lainauksenvalikoima, self.palaanappilainauksessa)
        QWidget.setTabOrder(self.palaanappilainauksessa, self.vahvistanappilainauksessa)
        QWidget.setTabOrder(self.vahvistanappilainauksessa, self.palaanappipalautuksessa)
        QWidget.setTabOrder(self.palaanappipalautuksessa, self.vahvistanappipalautuksessa)
        QWidget.setTabOrder(self.vahvistanappipalautuksessa, self.historianappi)
        QWidget.setTabOrder(self.historianappi, self.paivahistoriassa)
        QWidget.setTabOrder(self.paivahistoriassa, self.tavarahistoriassa)
        QWidget.setTabOrder(self.tavarahistoriassa, self.henkilohistoriassa)
        QWidget.setTabOrder(self.henkilohistoriassa, self.haenappi)
        QWidget.setTabOrder(self.haenappi, self.haunperuutusnappi)
        QWidget.setTabOrder(self.haunperuutusnappi, self.palaanappihistoriassa)
        QWidget.setTabOrder(self.palaanappihistoriassa, self.lainausvalikoimalista)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.lainausnappi.setText(QCoreApplication.translate("MainWindow", u"Lainaus", None))
        self.palautusnappi.setText(QCoreApplication.translate("MainWindow", u"Palautus", None))
        self.historianappi.setText(QCoreApplication.translate("MainWindow", u"Historia", None))
        self.tervetuloa.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'MS Shell Dlg 2'; font-size:12pt;\">Tervetuloa</span></p></body></html>", None))
        self.otsikkolainaus.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Lainaus</span></p></body></html>", None))
        ___qtablewidgetitem = self.lainausvalikoimalista.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Tavara 1", None))
        ___qtablewidgetitem1 = self.lainausvalikoimalista.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Tavara 2", None))
        ___qtablewidgetitem2 = self.lainausvalikoimalista.verticalHeaderItem(0)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Tavara", None))
#if QT_CONFIG(tooltip)
        self.lainausvalikoimalista.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><br/></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.palaanappilainauksessa.setText(QCoreApplication.translate("MainWindow", u"Palaa", None))
        self.vahvistanappilainauksessa.setText(QCoreApplication.translate("MainWindow", u"Vahvista", None))
        self.palaanappipalautuksessa.setText(QCoreApplication.translate("MainWindow", u"Palaa", None))
        self.vahvistanappipalautuksessa.setText(QCoreApplication.translate("MainWindow", u"Vahvista", None))
        self.palautus.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'MS Shell Dlg 2'; font-size:12pt;\">Palautus</span></p></body></html>", None))
        self.historia.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">Historia</span></p></body></html>", None))
        self.haenappi.setText(QCoreApplication.translate("MainWindow", u"Hae", None))
        self.tavarahistoriassa.setItemText(0, QCoreApplication.translate("MainWindow", u"Tavara", None))

        self.henkilohistoriassa.setItemText(0, QCoreApplication.translate("MainWindow", u"Henkil\u00f6", None))
        self.henkilohistoriassa.setItemText(1, QCoreApplication.translate("MainWindow", u"Henkil\u00f6", None))

        self.haunperuutusnappi.setText(QCoreApplication.translate("MainWindow", u"Peruuta", None))
        ___qtablewidgetitem3 = self.historialista.horizontalHeaderItem(0)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Lainattu", None))
        ___qtablewidgetitem4 = self.historialista.horizontalHeaderItem(1)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Palautettu", None))
        ___qtablewidgetitem5 = self.historialista.verticalHeaderItem(0)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"P\u00e4iv\u00e4", None))
        ___qtablewidgetitem6 = self.historialista.verticalHeaderItem(1)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"Tavara", None))
        ___qtablewidgetitem7 = self.historialista.verticalHeaderItem(2)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"Henkil\u00f6", None))
        self.palaanappihistoriassa.setText(QCoreApplication.translate("MainWindow", u"Palaa", None))
    # retranslateUi
